### ISSUE TITLE
Coral color is too darker and looks like compile errors

### ISSUE THREAD

**Issue by michaem** [one-dark/jetbrains-one-dark-theme#118]
One Dark Theme has one of the best color scheme among others themes in the Idea Market.
All colors consistently looks and same as there're in a Google Material Design.
But one color - 'coral', using for dynamic fields such as in Kotlin, looks too darker like 'compiler errors' in the default theme. Especially, when you share your code on different monitors and TVs without Retina display.
Some code sample, with default **'coral' color = e06c75** of the one_dark_theme
<img width="500" alt="Screenshot 2019-12-26 at 18 24 32" src="https://user-images.githubusercontent.com/18052928/71474444-0a8eb800-280e-11ea-9b73-4064cc51ab5d.png">

If we take same color, in the color system of Material Design (https://material.io/design/color/the-color-system.html#tools-for-picking-colors), and move to 1 value lighter, then will got 
**coral = eb959c**. On a code
<img width="527" alt="Screenshot 2019-12-26 at 18 40 37" src="https://user-images.githubusercontent.com/18052928/71474700-40806c00-280f-11ea-8236-3e16b1a24784.png">
Now it doesn't look like 'compile error' for dynamic fields. (In our opinion)

I can move this fix in an additional separate theme named by 'one_dark_material'. 
What do you think about this improvement and contribute it here for all?

P.S.
Also, I've checked other colors, they consistently same as in the Material Design color palette, except 'coral' color with e06c75 value.

**Comment by mskelton** [comment]
@michaem Thank you very much for your detailed write up and explanation.  The current hex color used for coral was picked to match with the color used in the original Atom One Dark theme.  Because the color matches with the Atom theme and other One Dark theme (i.e. VS Code), changing the coral color would not follow the goals of this theme to stay as true to the original theme as possible.

I'm also not to fond of the idea of adding an additional theme variant for this color as it seems like it would add more complexity and confusion considering that this is the first time this issue was brought up.

I'm sorry that this probably isn't the answer you were hoping for, but hopefully this helps to explain my position when fielding requests like this one.

Thanks and merry Christmas!

**Comment by michaem** [comment]
@mskelton Oh, thanks for answer! That's why I didn't created any pull-request before see your opinion. I'm understand that and thought too, that moving to another theme for one changing of color property not good decision.
Any way, I still will be use this theme and continue to help you by contributing some improvements, fixing bugs , if they will been found.

Thank you for answer! Merry Christmas too!

**Comment by mskelton** [comment]
Thank you for your understanding and for your willingness to give up some of your time to contribute to this theme.  This theme would not be where it is today without the help of the many people who have been so generous in opening issues and giving feedback on the theme.  Thank you!
