### ISSUE TITLE
Problem with theme persistence in Pycharm 2020.1.2 on Windows 10 Pro

### ISSUE THREAD

**Issue by skrubbel** [one-dark/jetbrains-one-dark-theme#171]
This is my absolute favourite theme for Pycharm and Rider - Thank you for that. But I have had to uninstall it after upgrading to the latest version.

Steps of reproduction:

1.  After the upgrade I select the theme under Settings -> Appearance & Behaviour -> Appearance -> Theme
2. When I look at Settings -> Editor -> Color Scheme -> Scheme a scheme with the title "One Dark Generated" appears.
3. The theme appears to be working correctly.
4. When I close Pycharm and re-open it again The UI theme has reverted back to The Default Light theme, and the editor appears to have shifted to the Darcula theme. One Dark and One Dark Generated still appears in the Theme and Scheme settings.

**Comment by Unthrottled** [comment]
Hey! I have a couple of workarounds you can try, before I get a solid fix out for this. This is a tricky bug that only happens after first install (I've had a hard time trying to reproduce it).

If you want to give v4 a second chance, [you can try this](https://github.com/one-dark/jetbrains-one-dark-theme/issues/172#issuecomment-653230480) That worked for me when I got stuck.

If you don't want to do that, you can revert back to v3.3.6. That release should be good up to 2020.1. You can follow [these instructions](https://github.com/one-dark/jetbrains-one-dark-theme/issues/172#issuecomment-653231188). That release is simple, has less moving parts, and does not have this issue.

Thank you for your patience and understanding.

**Comment by Unthrottled** [comment]
I decided to revert the configurable theme options in favor of a consistent and reliable theme user experience. Please upgrade to the stable v5.0.0.

 I find that this issue is unacceptable to have at the moment. I will re-visit the configurable theme options in a later date, when I have more time to flesh out all of the quirks of making the platform have configurable themes. 
 
Thank you for your patience and understanding!
