### ISSUE TITLE
Selection is not obvious in code complete menu

### ISSUE THREAD

**Issue by waltcow** [one-dark/jetbrains-one-dark-theme#213]
**Describe the bug**

Selection is not obvious in code complete menu

**To Reproduce**

1. one dark vivid color schema

**Expected Behavior**

**Environment**

**Screenshots**

![image](https://user-images.githubusercontent.com/3941174/110573304-fe361700-8195-11eb-8f9c-828abfee4f40.png)

**Comment by Unthrottled** [comment]
Are you referring to the row selection background or the character selection match foreground color?

**Comment by waltcow** [comment]
![image](https://user-images.githubusercontent.com/3941174/110748450-b0dfa580-827a-11eb-8635-18aedb4fcbff.png)

The popup menu for code auto complete

@Unthrottled

**Comment by Unthrottled** [comment]
Sorry for not being clear.

Are you referring to the row selection background (I colored blue) or the character selection match foreground color (I colored red)? Or is it something else?

![image](https://user-images.githubusercontent.com/15972415/110780118-f32cc680-8229-11eb-8f6f-323f5f08d149.png)

**Comment by waltcow** [comment]
> Sorry for not being clear.
> 
> Are you referring to the row selection background (I colored blue) or the character selection match foreground color (I colored red)? Or is it something else?
> 
> ![image](https://user-images.githubusercontent.com/15972415/110780118-f32cc680-8229-11eb-8f6f-323f5f08d149.png)

I am referring to the row selection background (colored blue)

**Comment by Unthrottled** [comment]
@waltcow 

Since that's just like, your opinion, I've added a feature to the [themed components plugin](https://github.com/Unthrottled/themed-components#themed-components) where you can [customize the selection color](https://github.com/Unthrottled/themed-components#completion-window-color-customizations) to something that suits yourself .

_Note_: the version with completion window customization isn't published yet so you'll have to follow the **Manual Installation** instructions.
