### ISSUE TITLE
PyCharm Jupyter Preview Window is not Themed

### ISSUE THREAD

**Issue by IBNobody** [one-dark/jetbrains-one-dark-theme#216]
**Describe the bug**

When using One Dark Vivid Italic (or any other One Dark theme), the preview pane of Jupyter Notebooks defaults to Dracula.

Opening/closing the Jupyter Notebook does not resolve this. Opening/closing PyCharm does not resolve this.

**To Reproduce**

1. Create a Jupyter Notebook.

**Expected Behavior**

The Preview Pane should be properly themed.

**Environment**

PyCharm 2021.1.1 (Professional Edition)
Build #PY-211.7142.13, built on April 21, 2021
Subscription is active until April 29, 2022.
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: com.markskelton.one-dark-theme (5.1.5), net.vektah.codeglance (1.5.4), com.microsoft.vso.idea (1.161.1), com.leinardi.pycharm.pylint (0.12.2), R4Intellij (211.6693.2), ru.meanmail.plugin.requirements (2021.4-211)

**Screenshots**

![image](https://user-images.githubusercontent.com/5863888/117050694-43308280-acdb-11eb-9b00-189719a8a6eb.png)

**Comment by Unthrottled** [comment]
Hmm, I don't know if that is theme-able by plugins. I am pretty sure that it is a chromium rendered window. You can right click and view page source and dev tools. I'll ask and see.

BTW, I think there are [jupytertheme](https://github.com/dunovank/jupyter-themes) which has `onedork` which is pretty similar

**Comment by Unthrottled** [comment]
Alright, so the current answer is "No, there is no way to apply any custom styling (css or otherwise) before HTML is rendered in the editor". This is something that could only be controlled by the Jupyter Plugin (and however it renders the html) and not this plugin. [Link to relevant slack thread](https://jetbrains-platform.slack.com/archives/C5U8BM1MK/p1620861297061600)

If this changes in the future, I'll might revisit this, but for the time being there isn't anything this plugin can do.

Thanks for taking the time to submit this detailed issue though.
