### ISSUE TITLE
Where can I setting the color?

### ISSUE THREAD

**Issue by linmii** [one-dark/jetbrains-one-dark-theme#235]
Where can I set the foreground color marked in the red box on the search or replace popup? It's hard to see clearly.
![image](https://user-images.githubusercontent.com/17309471/135020550-813ea006-092a-4a43-b1dc-d88a1d5da071.png)

**Comment by Unthrottled** [comment]
I agree that that it is hard to see. 

However, I think this was by design, repeated attributes in the find panel are dimmed

Here is the code that defines that:

https://github.com/JetBrains/intellij-community/blob/3035233ecff58e117bafd0d42bb2a7baf18839c9/platform/lang-impl/src/com/intellij/find/impl/FindPopupPanel.java#L1941

Component.infoForeground is used by a bunch of things, so I am not going to change the current value. I am not going to make this plugin override platform code. 

If you still want this fixed, I might be able to come up with a hack in the [themed components plugin](https://github.com/Unthrottled/themed-components), feel free to submit [an issue there](https://github.com/Unthrottled/themed-components/issues), asking for customization of this attribute. 

Thank you!
