### ISSUE TITLE
not distinguishable for identifier under caret

### ISSUE THREAD

**Issue by yantaozhao** [one-dark/jetbrains-one-dark-theme#265]
This is a great theme i've used so far.

However the `identifier under caret` is a little bit undistinguishable, especially when code span many rows. so i have to hack by changing the style :
- identifier under caret: add effects by `bordered` color (my case: 606060)
- identifier under caret(write): add effects by `bordered` color (my case: C0C0C0)

Wanting some more robust way to improve it.
thx.

**Comment by Unthrottled** [comment]
Hey!

I don't know if this helps, but the `Error stripe mark` is something you can also look out for, it shows up in the right hand scroll gutter. That helps me identify items under the caret that aren't on the window at the moment.

<img width="846" alt="Screen Shot 2022-09-20 at 5 18 16 PM" src="https://user-images.githubusercontent.com/15972415/191375292-4931c65e-8974-41ea-821a-242b4dd9eaad.png">

I don't know if that was the advice you were looking for, but it's what I've got. 😄 

Since what is distinguishable & also subtle is subjective and depends on various other factors such as: monitor brightness, monitor color, color profiles, etc. I'll leave this be, since you have the ability to modify it to your tastes. 

I'm open for more discussion in this thread, but I'm closing this for now, thanks!

**Comment by yantaozhao** [comment]
Have a look at gutter is sometimes right, and your example looks very clear. But it's not a solid way, as there maybe other distractions in the shared area. e.g.(a common real case):

![image](https://user-images.githubusercontent.com/9587405/191458203-037b07ec-5806-4bfc-897c-fb5a6f47bda3.png)

So, perhaps getting the identifier more recognizable directly inside codes is an better way. 🤔

**Comment by Unthrottled** [comment]
> So, perhaps getting the identifier more recognizable directly inside codes is an better way

Yeah the `Error Stripe mark` was a recommendation in addition to you adding the bordered `effect` and changing the `Background` of the Identifier Under caret to suite your tastes.
