### ISSUE TITLE
Small UI issue in NuGet window for experimental UI

### ISSUE THREAD

**Issue by CameO73** [one-dark/jetbrains-one-dark-theme#267]
**Describe the bug**
When the experimental UI is enabled (Registry... > enable ide.experimental.ui), a small UI issue is present in the NuGet window when using One Dark. This issue is not present when using the standard Jetbrains Dark theme or when disabling the experimental UI.

**To Reproduce**
1. Open the Registry... (e.g. via Search Everywhere)
2. Enable the **ide.experimental.ui** setting
3. Restart the IDE 
4. Open the NuGet window (Alt-7)

**Expected Behavior**
Background color correctly applied around Solution / All feeds / Prerelease elements

**Environment**
JetBrains Rider 2022.2.3
Build #RD-222.4167.23, built on September 9, 2022
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET 6.0.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 16
Registry:
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false
    rdclient.asyncActions=false

Non-Bundled Plugins:
    some.awesome (1.14)
    me.seclerp.rider.plugins.efcore (222.1.1)
    eu.gillissen.rider.usersecrets (1.2.0)
    com.markskelton.one-dark-theme (5.7.0)
    com.intellij.resharper.StructuredLogging (2022.2.0.241)
    Key Promoter X (2022.2)
    zielu.gittoolbox (212.9.9)
    mobi.hsz.idea.gitignore (4.4.2)
    izhangzhihao.rainbow.brackets (6.26)
    com.intellij.resharper.azure (3.50.0.1490-2022.2)
    Abc.MoqComplete.Rider (2022.2.0.2)

**Screenshots**
With experimental UI disabled:
![image](https://user-images.githubusercontent.com/17951614/192318143-416eb876-1440-4197-adbd-0e03c377effe.png)

With experimental UI enabled:
![image](https://user-images.githubusercontent.com/17951614/192318292-1b3d1547-19ce-4987-b185-e830cbf2db16.png)

**Comment by Unthrottled** [comment]
Looked into this, I don't think there is a good fix for this.

Looks like there is an issue with the padding/spacing, because the `ToolWindow.background` is bleeding out.

![image](https://user-images.githubusercontent.com/15972415/192511875-f794b9d0-64d8-46f4-8883-18dc2b54651f.png)

When I set the color to match the header, It makes other stuff look awful

![image](https://user-images.githubusercontent.com/15972415/192511990-6dc0a23a-4e25-43dd-a85a-daba94708074.png)

So I'm not going fix this issue in the plugin. Once JetBrains decides what they want to do with the new UI, then maybe we can revisit this. I'm going to close the issue, but I'm willing to provide guidance if you want to fix the issue yourself. 

Thanks for reporting, and sorry about having to deal with the annoying padding issue!

**Comment by CameO73** [comment]
Thanks for looking into this! I had no idea the background was used for the package list as well -- so a quick fix is out of the question. Waiting for the release with the final UI is definitely the best course of action.
