### ISSUE TITLE
More visible popup borders needed

### ISSUE THREAD

**Issue by tanmatra** [one-dark/jetbrains-one-dark-theme#270]
Please change border color for popup windows, it's sometimes almost impossible to tell where popup edges is.
I think it should be more darker.

Or, at least, I will be glad to learn how to do it using the configuration file.

Compare: 

One dark:
![one dark](https://user-images.githubusercontent.com/708023/197705389-ff741713-b546-4e69-b56a-b9b1ec6ffc6c.png)

Darcula:
![darcula](https://user-images.githubusercontent.com/708023/197705344-cef78697-b861-4e68-bbba-085123bce069.png)

**Comment by Unthrottled** [comment]
I might have some time in the future (maybe this weekend or the next) to investigate what could be done, or how you could configure it. Thanks!

**Comment by Unthrottled** [comment]
Looks like it is the `Popup.borderColor` look and feel property that controls what you are looking for.

![image](https://user-images.githubusercontent.com/15972415/201449091-62e0ca33-1854-40e8-992b-f025aa05eca3.png)

Seems as though it was added in such a way to be discreet. Since this is a personal preference (having the border doesn't add much value IMO), I'll leave it to you to customize it yourself.

I don't think the platform supports overriding one off look and feel. Guess that's what themes are for 😄 

You've got a couple options:

- Maintain a fork of this theme with your customizations (the project doesn't update very much)
- [Ask nicely for me to add the one-off color customization in the theme components plugin](https://github.com/Unthrottled/themed-components/issues/new?assignees=&labels=&template=feature_request.md&title=).
