### ISSUE TITLE
Parameters and variables are multi colored

### ISSUE THREAD

**Issue by aidando73** [one-dark/jetbrains-one-dark-theme#273]
I don't know if this is a bug or a feature I've accidentally turned on or an issue with another part of intellij. Could someone point me in the right direction?

**Describe the bug**

Parameters and variables seem to be multi-colored (see screenshot below). I wasn't like this a few days ago. And other themes don't have the same issue.

**To Reproduce**

1. No steps - out of the box behaviour.

**Expected Behavior**

Parameters and variables to be a consistent color like other themes. E.g., The vscode theme:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/43259657/202085291-aa289aa6-d738-474c-a9a0-f3c83acca9fa.png">

**Environment**

Mac
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
One Dark theme version 5.7.1

**Screenshots**

<img width="756" alt="image" src="https://user-images.githubusercontent.com/43259657/202084666-2b673afc-7089-4d6e-bfaa-65fc276fe4b6.png">

**Comment by Unthrottled** [comment]
Ah, this is due to the rainbow bracket plugin you have installed. [A Recent update](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/CHANGELOG.md#change-log) enabled [semantic highlighting](https://www.jetbrains.com/help/idea/configuring-colors-and-fonts.html#semantic-highlighting) by default.

Just go to the rainbow bracket settings and disable `Rainbow Variables`.
