### ISSUE TITLE
Vivid Theme Render issues

### ISSUE THREAD

**Issue by KevinMeinon** [one-dark/jetbrains-one-dark-theme#276]
**Describe the bug**

If I use One Dark Vivid theme (has to be Vivid) and Git plugin for PyCharm, I will get render issues once Git VCS is active. 
This seems to be related to private repos.  

Video of the issue (make sure to pay attention to the scroll-bar in the last third of the video): 
https://streamable.com/wmrvkz

**To Reproduce**

1. Enable Git plugin
2. Enable One Dark Vivid theme
3. Clone a (private) repo
4. ...
5. Profit!

**Expected Behavior**

There should be no render bugs.

**Environment**

PyCharm 2022.2.4 (Professional Edition)
Build #PY-222.4459.20, built on November 17, 2022
Licensed to Kevin Meinon
Subscription is active until December 20, 2022.
For educational use only.
Runtime version: 17.0.5+7-b469.71 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.valueTooltipAutoShowOnSelection=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    indent-rainbow.indent-rainbow (2.0.2)
    com.vermouthx.idea (1.14.2)
    com.markskelton.one-dark-theme (5.7.1)
    com.intellij.ideolog (203.0.30.0)
    com.github.copilot (1.1.35.2063)
    com.4lex4.intellij.solarized (2.4.0)
    ru.meanmail.plugin.requirements (2022.4)
    izhangzhihao.rainbow.brackets (2022.3.4-ij)
    net.seesharpsoft.intellij.plugins.csv (3.0.1-222)
    CMD Support (1.0.5)

**Screenshots**

Video: https://streamable.com/wmrvkz

**Comment by Unthrottled** [comment]
Hey, I am hesitant to follow links outside of GitHub. GitHub does support [attaching video files](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files), please attach the file to the issue here so I can view it within GitHub. Thanks for understanding.

**Comment by KevinMeinon** [comment]
Streamable is a well known site, but sure thing, will upload it here.

https://user-images.githubusercontent.com/3797846/203823631-cf1930ae-55db-4091-868c-cdcfcd4cb9d0.mp4

**Comment by Unthrottled** [comment]
Hey! Thanks for taking the time to report the issue.

I've tried to reproduce the issue, and have not been able to.

I highly doubt that this is an issue with this plugin, [as it just uses the theming APIs provided by the platform](https://plugins.jetbrains.com/docs/intellij/theme-structure.html#theme-description-file) and nothing else special.

If you could, uninstall the One Dark theme and try to install/isolate other themes such as:
- https://plugins.jetbrains.com/plugin/12100-dark-purple-theme
- https://plugins.jetbrains.com/plugin/12334-gradianto

I have a feeling that it may be an issue with the platform itself & not the plugin. It might also be an issue with another one of the plugins.

If you could validate that this is the issue happens with other theme plugins, that'd be cool.

That being said, the underlying fix will most likely not originate in this plugin.
I will most likely close the issue here and help point you in the right direction to fix your issue.

**Comment by Unthrottled** [comment]
I am fairly confident that the fix won't be done in this plugin.  This sounds like either an issue on your machine or an issue with the platform itself. 

Am going to close this issue for now.

Thanks for understanding & taking the time to submit the issue.
