### ISSUE TITLE
Improvement: selected color on variable rename

### ISSUE THREAD

**Issue by x1unix** [one-dark/jetbrains-one-dark-theme#33]
Hello, when I do some class or variable rename, selected text is darker than a section for rename.
I caught myself thinking that this confuses me often, because selected text usually is highlighted.
But currently only section around selected text looks highlighted, not the selected text.

Can you change please selection color vise-versa (see screenshot below)

![изображение](https://user-images.githubusercontent.com/9203548/57004449-bb897800-6bd7-11e9-8e43-bbbebbaadd9a.png)

**Steps to reproduce:** 

* Select some variable, class field or class name
* Right click, **Refactor | Rename**

**Comment by mskelton** [comment]
I believe this is the default behavior of IntelliJ and not something I would be able to fix.  Additionally, I think that making it all the same color would be confusing because you would not be able to distinguish where your selection was as it would be the same color as the rest of the refactor box.

**Comment by x1unix** [comment]
@markypython I meant to make selected text background lighter and unselected section darker.
It's sad that it's impossible to fix but ok :(
