### ISSUE TITLE
Add OneLight flavour

### ISSUE THREAD

**Issue by astrolemonade** [one-dark/jetbrains-one-dark-theme#66]
**Describe the proposed feature**

First of all, I understand that the name of the repository is **One Dark** . I think it would be a good feature to have a light version of the theme. I would really like to have a light version of the theme, I usually use light themes at day and dark them at night. 
I think it would be little work to do to make this happen, changing the background to white or something close to white and tweaking some colors to make them easy to distinguish from the background.
Let me know what you think !

**Comment by mskelton** [comment]
While I'm not opposed to the idea of having the light version of this theme, I think it is so different from this theme that it should be in a separate repository/IntelliJ plugin.  Because this theme is just a color theme and doesn't have any other customizations or features, most of this repo would have to change.

**Comment by astrolemonade** [comment]
I understand what you said! Maybe in the future I will give it a try.

**Comment by mskelton** [comment]
If you do, let me know as I would be happy to share any thoughts or experiences from building this theme.  Cheers!

**Comment by astrolemonade** [comment]
Of course, @markypython

mar., 25 iun. 2019, 01:35 Mark Skelton <notifications@github.com> a scris:
