### ISSUE TITLE
Docstring

### ISSUE THREAD

**Issue by ktconnolly** [one-dark/jetbrains-one-dark-theme#81]
Is there anyway to stop the param and return inside the docstring from being highlighted?  

![Screenshot from 2019-07-30 16-18-18](https://user-images.githubusercontent.com/44116267/62142360-1c634200-b2e6-11e9-906a-cf5c7f22787c.png)

**Comment by mskelton** [comment]
That is intentional, but you may be able to change it by adjusting the theme.  I'll have to take a look this evening as I don't have access to PyCharm right now.

**Comment by mskelton** [comment]
@KTConnolly There are two settings that control that color.  I have attached screenshots of both.  If you want to disable it for just Python, adjust the first setting.  Otherwise, if you want to disable it globally, adjust the second setting.

### Setting in Python

![2019-07-30_18-18-46](https://user-images.githubusercontent.com/25914066/62172849-6570c180-b2f9-11e9-97bd-d30bb75bfa15.png)

### Setting in Language Defaults

![2019-07-30_18-20-26](https://user-images.githubusercontent.com/25914066/62172851-66a1ee80-b2f9-11e9-839d-10d4f18c6d18.png)

**Comment by mskelton** [comment]
Closing this as not an issue.  This behavior is intentional and can be modified if it is not desired.

Thanks for the question!

**Comment by ktconnolly** [comment]
Thanks!
