### ISSUE TITLE
File names are not readable

### ISSUE THREAD

**Issue by levani** [one-dark/jetbrains-one-dark-theme#90]
**Describe the bug**
Not sure what's the name of this area and why it has a different background color but file names are not very readable here...

**Expected behavior**
File names must be more readable.

**Screenshots**
![Screenshot_18](https://user-images.githubusercontent.com/184472/64760460-c7545600-d54a-11e9-8d86-0abe0daca9b9.png)

**Comment by mskelton** [comment]
@levani The orange color is because of file colors which is something I don't use in IntelliJ as I find it very ugly.  Because I don't use it, I find it very difficult when attempting to improve the file colors for this theme.  As such, I try to lean on people who use this theme to provide helpful suggestions about how to improve the file colors.

As you will notice in your screenshot, the color of the locales directory looks very good as it clearly is identified as an ignored folder.  The file colors is where this gets tricky.

Do you have any suggestions of alternate colors to use for filename background?  I would appreciate any thoughts you have.

**Comment by levani** [comment]
@markypython
These directories are not inside `locales` folder. They are inside `node_modules` folder, which is marked as `library root`.

I think this `library root` case must be handled the same way as excluded folders are handled. Background color is the same here and file/folder names are a much lighter (screenshot below).

![Screenshot_19](https://user-images.githubusercontent.com/184472/64868259-015b5000-d650-11e9-8b9b-dd89d8082453.png)

**Comment by mskelton** [comment]
This will be fixed in #92

**Comment by mskelton** [comment]
Fixed in version [3.0.0](https://github.com/one-dark/jetbrains-one-dark-theme/releases/tag/v3.0.0)

**Comment by markypython** [comment]
@allcontributors add @levani to design

**Comment by markypython** [comment]
@allcontributors add levani to design

**Comment by mskelton** [comment]
@allcontributors add levani to design
