### ISSUE TITLE
White background after updating

### ISSUE THREAD

**Issue by TheSilentPro** [one-dark/jetbrains-one-dark-theme#99]
**Describe the bug**

In update 3.0.0 the background is now white, it was never like that.
Only after updating it did this.

**Expected behavior**

To be dark and not white

**Screenshots**

![image](https://user-images.githubusercontent.com/46107752/67149034-c7144c80-f2a6-11e9-8e2f-ad00ed95fbc7.png)

**Comment by mskelton** [comment]
You will probably just need to go into the IntelliJ preferences and deselect "One Dark" from the appearance dropdown and then reselect it.  I knew this could be a potential issue after a major change I made to this theme to include the vivid variant which is why I released the theme as version 3.0.0 to follow semver for a breaking change.

**Comment by TheSilentPro** [comment]
Yeah, that fixed it.
Just went to the preferences and selected one dark and it worked.
